// <auto-generated />
using FilmStore.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace FilmStore.Data.EF.Migrations
{
    [DbContext(typeof(FilmStoreDbContext))]
    [Migration("20230613171944_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FilmStore.Data.FilmDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IMDb")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "russian")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "Author" });

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GiST");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Майкл Бэй",
                            Description = "Таинственное событие из прошлого Земли угрожает разжечь настолько масштабную войну, что Трансформеры в одиночку не смогут спасти планету. Сэм Уитвики и автоботы должны сражаться с тьмой, чтобы защитить наш мир от десептиконов.",
                            IMDb = "ID1399103",
                            Price = 9.99m,
                            Title = "Трансформеры: Темная сторона Луны"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Джордж Лукас",
                            Description = "Еще совсем недавно было трудно поверить, что убеленный сединами наставник Оби-Ван Кеноби когда-то был безусым юнцом, а повергающий Галактику в трепет Император Палпратин - лишь амбициозным сенатором. И совершенно невозможно представить зловещего Дарта Вейдера маленьким мальчиком, который живет в рабстве на Татуине, а по ночам мечтает о далеких звездах. Мы попадаем в то самое время, когда рыцари-джедаи еще хранят мир и спокойствие в Галактике. Но темная сила, готовая поглотить планеты и народы, уже пробудилась, и только древнее пророчество дждаев об избранном, который принесет равновесие в Силу, дает надежду в преддверии катастрофы. Скрытая угроза нависла над Республикой, простоявшей не одну тысячу лет, но теперь погрязшей в пучине политических разногласий и интриг. Мастер-джедай Квай-Гон Джин и его ученик Оби-Ван Кеноби приходят на помощь королеве Амидале, которая стремиться спасти планету Набу от блокады алчной Торговой Федерации. Бегство с Набу приводит джедаев на песчаные просторы Татуина, где им суждена встреча с Энакином Скайуокером. .Здесь начинается история, которая впоследствии станет легендой…",
                            IMDb = "ID0120915",
                            Price = 17.99m,
                            Title = "Звёздные войны: Эпизод 1 — Скрытая угроза"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Джордж Лукас",
                            Description = "Действие разворачивается через 10 лет после событий, описанных в первом эпизоде знаменитой саги. Республика все глубже погружается в пучину противоречий и хаоса. Движение сепаратистов, представленное сотнями планет и могущественным альянсом корпораций, грозит стать новой угрозой для Галактики, с которой не смогут справиться даже джедаи. Назревающий конфликт, заранее спланированный могущественными, но пока еще не разоблаченными силами, ведет к началу Клонических войн и к закату республики. Чтобы противостоять угрозе вселенских масштабов, Верховный канцлер Палпатин добивается консолидации власти в республике в своих руках и отдает приказ о создании республиканской армии для поддержки малочисленной группы джедаев в их борьбе с превосходящим противником.",
                            IMDb = "ID0121765",
                            Price = 19.99m,
                            Title = "Звёздные войны: Эпизод 2 — Атака клонов"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Мэтью Стовер",
                            Description = "Войны клонов бушуют по всей галактике. Зловещий Лорд Ситхов захватывает контроль над Республикой и развращает Энакина Скайуокера, чтобы тот стал его темным учеником, Дартом Вейдером. Оби-Ван Кеноби должен сразиться со своим павшим другом в эпической дуэли на световых мечах.",
                            IMDb = "ID0121766",
                            Price = 19.99m,
                            Title = "Звездные войны: Эпизод 3 — Месть ситхов"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Гор Вербински",
                            Description = "Капитан пиратов Джек Воробей должен завладеть легендарным сундуком Мертвеца, чтобы обмануть смерть и вечное проклятие. Но открытое море таит в себе множество препятствий, включая могучего кракена!",
                            IMDb = "ID 0383574",
                            Price = 17.99m,
                            Title = "Пираты Карибского моря: Сундук мертвеца"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Гор Вербински",
                            Description = "Когда пиратский капитан Джек Воробей оказывается в ловушке в море песка в шкафчике Дэви Джонса, его товарищи по кораблю начинают отчаянные поиски, чтобы найти и спасти его. ",
                            IMDb = "ID0449088",
                            Price = 17.99m,
                            Title = "Пираты Карибского моря: на краю света"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Гор Вербински",
                            Description = "Капитана Джека Воробья преследует старый соперник капитан Салазар и команда смертоносных призраков, которые сбегают из Дьявольского треугольника, полные решимости убить каждого пирата в море...особенно его самого. ",
                            IMDb = "ID1790809",
                            Price = 19.99m,
                            Title = "Пираты Карибского моря: Мертвецы не рассказывают сказок"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Марк Невелдайн",
                            Description = "Джонни Блейз рано остался сиротой, и воспитанием юного сорвиголовы занялся лучший мотогонщик Америки Крэш Симпсон. С годами Джонни стал полноправным членом семьи Симпсонов и когда Крэш оказался смертельно болен, Блейз был готов пойти на всё ради спасения жизни приёмного отца… в том числе и на сделку с Сатаной! Теперь Джонни лучший в мире каскадёр днём и Призрачный гонщик ночью! Искренняя любовь невинной Роксаны Симпсон не даёт Сатане получить власть над душой Джонни, но долго ли влюблённые смогут противостоять власти Владыки ада? Поможет ли им Деймон Хеллстром, Сын Сатаны? Или спасение стоит искать в древней индейской магии? А может быть, стоит просто изо всех сил гнать по шоссе? Прижмитесь к обочине, смертные, на дорогу выезжает Призрачный гонщик! Станьте свидетелем рождения самого знаменитого мистического героя Marvel! Вас ждут безумные погони, смертельно опасные трюки, схватки с потусторонними слугами дьявола, жуткие обряды индейских шаманов и история о настоящей, чистой любви! В книге собраны выпуски комиксов, в которых состоялись первые появления персонажей, которые окажут серьёзное влияние на мистическую сторону вселенной Marvel, в том числе Деймона Хеллстрома, Сына Сатаны! ",
                            IMDb = "ID0259324",
                            Price = 19.99m,
                            Title = "Призрачный Гонщик"
                        });
                });

            modelBuilder.Entity("FilmStore.Data.OrderDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DeliveryDescription")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("money");

                    b.Property<string>("DeliveryUniqueCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PaymentDescription")
                        .HasColumnType("text");

                    b.Property<string>("PaymentParameters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentServiceName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FilmStore.Data.OrderItemDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FilmStore.Data.OrderItemDTO", b =>
                {
                    b.HasOne("FilmStore.Data.OrderDTO", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FilmStore.Data.OrderDTO", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
